[config]
autoboot=0
autoboot_list=0
bootwait=1
backlight=100
noticker=0
autohosoff=0
autonogc=1
updater2p=0
bootprotect=0

[mario]
# move the scripts/mario.te to startup.te to boot that script 
rename=scripts/mario.te
# boot tegra explorer payload to executre startup.te
payload=bootloader/payloads/TegraExplorer.bin

[luigi]
# move the scripts/luigi.te to startup.te to boot that script 
rename=scripts/luigi.te
# boot tegra explorer payload to executre startup.te
payload=bootloader/payloads/TegraExplorer.bin
